chore: shellcheck issues and allow custom install location (#29)

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 # Copyright (c) 2023 Purple Clay
 #
@@ -22,11 +22,12 @@
 
 # Install script is heavily based on: https://github.com/Masterminds/glide.sh/blob/master/get
 
-: "${USE_SUDO:='true'}"
-: "${GPG_IMPORT_INSTALL_DIR:='/usr/local/bin'}"
+: "${USE_SUDO:=true}"
+: "${INSTALL_DIR:=/usr/local/bin}"
 
-HAS_CURL="$(type "curl" &> /dev/null && echo true || echo false)"
-HAS_WGET="$(type "wget" &> /dev/null && echo true || echo false)"
+APP_NAME="gpg-import"
+HAS_CURL="$(type curl >/dev/null && echo true || echo false)"
+HAS_WGET="$(type wget >/dev/null && echo true || echo false)"
 
 initTarget() {
   case "$(uname -s)" in
@@ -46,8 +47,8 @@ initTarget() {
 }
 
 canDownload() {
-    local supported="x86_64-unknown-linux-musl\naarch64-unknown-linux-musl\nx86_64-apple-darwin\naarch64-apple-darwin\nx86_64-pc-windows-msvc\naarch64-pc-windows-msvc"
-    if ! echo "${supported}" | grep -q "${TARGET}"; then
+    _supported="x86_64-unknown-linux-musl\naarch64-unknown-linux-musl\nx86_64-apple-darwin\naarch64-apple-darwin\nx86_64-pc-windows-msvc\naarch64-pc-windows-msvc"
+    if ! echo "${_supported}" | grep -q "${TARGET}"; then
       echo "No prebuilt binary currently exists for target ${TARGET}."
       exit 1
     fi
@@ -60,49 +61,50 @@ canDownload() {
 
 download() {
   if [ -z "$DESIRED_VERSION" ]; then
-    if [ "${HAS_CURL}" == "true" ]; then
-      TAG="$(curl -s https://api.github.com/repos/purpleclay/gpg-import/releases/latest | grep "tag_name" | cut -d'"' -f4)"
-    elif [ "${HAS_WGET}" == "true" ]; then
-      TAG="$(wget -q https://api.github.com/repos/purpleclay/gpg-import/releases/latest -O - 2>&1 | grep "tag_name" | cut -d'"' -f4)"
+    if [ "${HAS_CURL}" = "true" ]; then
+      TAG="$(curl -s https://api.github.com/repos/purpleclay/$APP_NAME/releases/latest | grep "tag_name" | cut -d'"' -f4)"
+    elif [ "${HAS_WGET}" = "true" ]; then
+      TAG="$(wget -q https://api.github.com/repos/purpleclay/$APP_NAME/releases/latest -O - 2>&1 | grep "tag_name" | cut -d'"' -f4)"
     fi
   else
     TAG=${DESIRED_VERSION}
   fi
 
-  echo "Attempting to download gpg-import ${TAG}..."
+  echo "Attempting to download ${APP_NAME} version ${TAG}..."
 
   PACKAGE_TYPE="tar.gz"
-  if [ "${OS}" == "windows" ]; then
+  if [ "${OS}" = "windows" ]; then
     PACKAGE_TYPE="zip"
   fi
 
-  local archive="gpg-import-${TAG}-${TARGET}.${PACKAGE_TYPE}"
+  _archive="${APP_NAME}-${TAG}-${TARGET}.${PACKAGE_TYPE}"
 
-  DOWNLOAD_URL="https://github.com/purpleclay/gpg-import/releases/download/${TAG}/${archive}"
+  DOWNLOAD_URL="https://github.com/purpleclay/${APP_NAME}/releases/download/${TAG}/${_archive}"
   echo "$DOWNLOAD_URL"
-  DOWNLOAD_DIR="$(mktemp -dt gpg-import-install-XXXXXXX)"
-  GPG_IMPORT_FILE="${DOWNLOAD_DIR}/${archive}"
+  DOWNLOAD_DIR="$(mktemp -dt ${APP_NAME}-install-XXXXXXX)"
+  DOWNLOAD_FILE="${DOWNLOAD_DIR}/${_archive}"
 
-  if [ "${HAS_CURL}" == "true" ]; then
-    curl -L "$DOWNLOAD_URL" -o "$GPG_IMPORT_FILE"
-  elif [ "${HAS_WGET}" == "true" ]; then
-    wget -q -O "$GPG_IMPORT_FILE" "$DOWNLOAD_URL"
+  if [ "${HAS_CURL}" = "true" ]; then
+    curl -L "$DOWNLOAD_URL" -o "$DOWNLOAD_FILE"
+  elif [ "${HAS_WGET}" = "true" ]; then
+    wget -q -O "$DOWNLOAD_FILE" "$DOWNLOAD_URL"
   fi
 }
 
 install() {
-  echo "Installing gpg-import..."
+  echo "Installing ${APP_NAME}..."
+  test ! -d "$INSTALL_DIR" && mkdir -p "$INSTALL_DIR"
 
-  local extract_dir="$DOWNLOAD_DIR/gpg-import-$TAG"
-  mkdir -p "$extract_dir"
-  tar xf "$GPG_IMPORT_FILE" -C "${extract_dir}"
-  runAsRoot cp "${extract_dir}/gpg-import" "${GPG_IMPORT_INSTALL_DIR}/gpg-import"
+  _extract_dir="$DOWNLOAD_DIR/${APP_NAME}-${TAG}"
+  mkdir -p "$_extract_dir"
+  tar xf "$DOWNLOAD_FILE" -C "${_extract_dir}"
+  runAsRoot cp "${_extract_dir}/${APP_NAME}" "${INSTALL_DIR}/${APP_NAME}"
 
-  echo "Installed gpg-import to ${GPG_IMPORT_INSTALL_DIR}"
+  echo "Installed ${APP_NAME} to ${INSTALL_DIR}"
 }
 
 runAsRoot() {
-  if [ $EUID -ne 0 ] && [ "$USE_SUDO" = "true" ]; then
+  if [ "$(id -u)" -ne 0 ] && [ "$USE_SUDO" = "true" ]; then
     sudo "${@}"
   else
     "${@}"
@@ -110,62 +112,70 @@ runAsRoot() {
 }
 
 tidy() {
-
-  if [[ -d "${DOWNLOAD_DIR:-}" ]]; then
+  if [ -d "${DOWNLOAD_DIR:-}" ]; then
     rm -rf "$DOWNLOAD_DIR"
   fi
 }
 
 verify() {
   set +e
-  type "gpg-import" &> /dev/null
+  type "$APP_NAME" >/dev/null
   if [ "$?" = "1" ]; then
-    echo "gpg-import not found. Is ${GPG_IMPORT_INSTALL_DIR} on your PATH?"
+    echo "${APP_NAME} not found. Is ${INSTALL_DIR} on your PATH?"
     exit 1
   fi
 
   # Test version
-  INSTALLED_VERSION="$(gpg-import -V)"
-  if [ "${INSTALLED_VERSION}" != "gpg-import ${TAG}" ]; then
-    echo "Found version ${INSTALLED_VERSION} of gpg-import and not expected installed version of $TAG"
+  INSTALLED_VERSION="$($APP_NAME -V)"
+  if [ "${INSTALLED_VERSION}" != "${APP_NAME} ${TAG}" ]; then
+    echo "Found version ${INSTALLED_VERSION} of ${APP_NAME} and not expected installed version of $TAG"
     exit 1
   fi
   set -e
 }
 
 bye() {
-  local result=$?
-	if [ "$result" != "0" ]; then
-		echo "Failed to install gpg-import"
+  _result=$?
+	if [ "$_result" != "0" ]; then
+		echo "Failed to install ${APP_NAME}"
 	fi
   tidy
-	exit $result
+	exit $_result
 }
 
 help () {
-  echo "gpg-import install"
+  echo "${APP_NAME} installer"
   echo
   echo "Flags:"
-  echo -e "  -h, --help     print help for the installer"
-  echo -e "  -v, --version  download and install a specific version (default 'latest')"
-  echo -e "      --no-sudo  install without using sudo"
+  echo "  -d, --dir      a directory where the binary will be installed (default '$INSTALL_DIR')"
+  echo "      --no-sudo  install without using sudo"
+  echo "  -v, --version  download and install a specific version (default 'latest')"
+  echo "  -h, --help     Print help for the installer"
 }
 
 trap "bye" EXIT
 set -e
 
 # Parsing input arguments (if any)
-export INPUT_ARGUMENTS=("$@")
 set -u
-while [[ $# -gt 0 ]]; do
+while [ $# -gt 0 ]; do
   case $1 in
     '--version'|-v)
        shift
-       if [[ $# -ne 0 ]]; then
-           export DESIRED_VERSION="${1}"
+       if [ $# -ne 0 ]; then
+         export DESIRED_VERSION="${1}"
        else
-           echo -e "Please provide a valid version: e.g. --version v0.1.0 or -v v0.1.0"
-           exit 0
+         echo "Please provide a valid version: e.g. --version 0.3.0 or -v 0.3.0"
+         exit 0
+       fi
+       ;;
+    '--dir'|-d)
+       shift
+       if [ $# -ne 0 ]; then
+         INSTALL_DIR="${1}"
+       else
+         echo "Please provide a valid location for the install directory"
+         exit 0
        fi
        ;;
     '--no-sudo')
@@ -175,7 +185,9 @@ while [[ $# -gt 0 ]]; do
        help
        exit 0
        ;;
-    *) exit 1
+    *) help
+       echo
+       exit 1
        ;;
   esac
   shift
